[SQUASH]: build: bring back the stuff
    Makefile: Fix target display

    Change-Id: I07e60e6b9a6b09d798ca50c6295072828b643a50

    Generic target: Don't build Music, we have Apollo

    Change-Id: I3ff30b44dc53dcadb7155cfe69344810a5af77d7

    product: Remove MusicFX, we have DSPManager

    Change-Id: I6be4c766f83a91c2e6104cbaa18ee18abd7784cf

    Allow a device to generically define its own headers

    We have a few cases of devices including specific versions of projects
    just because of modified headers (msm_mdp.h comes to mind), and I just
    had enough of ifdeffing header files for specific cases (the P990 needs
    a lot of these).
    Now... if a target defines a TARGET_SPECIFIC_HEADER_PATH, any headers in
    there will take precedence over the standard ones; for example, on the
    p990, I have

    TARGET_SPECIFIC_HEADER_PATH := device/lge/p990/include

    which makes, for example, the
    device/lge/p990/include/hardware_legacy/AudioHardwareInterface.h be
    used instead of
    hardware/libhardware_legacy/include/hardware_legacy/AudioHardwareInterface.h
    whenever a source file uses <hardware_legacy/AudioHardwareInterface.h>

    Change-Id: I41b62668b60e3f62a6ebd3738d8d2675103a81e6

    envsetup: set OUT_DIR to an absolute path always

    OUT_DIR was set to $(TOPDIR)out previously,
    but $(TOPDIR) was null, so it was a relative path.
    This broke releasetools, inline kernel building, etc
    since they require absolute paths.
    Fix it so that it is set to $(shell readlink -f .)/out
    if $(TOPDIR) is null.

    Also remove hacks which checked if (OUT_DIR) was out
    and changed it to $(ANDROID_BUILD_TOP)/out to workaround
    the aforementioned problem.

    Change-Id: I459a3b1325a1bbea0565cd73f6acf160d4ed9b39

    Conflicts:
        core/base_rules.mk
        core/tasks/kernel.mk

    Change-Id: I52a7a6024f0f2b708c230e53c0152ed138726cc1

    envsetup: Set CUSTOM_BUILD environment variable

    This is used to gate a few features, including backuptool

    Change-Id: I02fee9e0765cca88c833bb0514762aa3b14642e3

    Add backuptool support to the releasetools system

    Pulled from CyanogenMod 10.1

     Conflicts:
        tools/releasetools/ota_from_target_files.py

    Change-Id: Iffd9a45865011ad9108508d31f79e53d609dd6f4

    Allow override of device asserts, including multi-device support.

    Set in board file with TARGET_OTA_ASSERT_DEVICE.
    (cherry-picked from commit 0f452f21fc9323b9d1fe746161761cf40aaa5030)

    Change-Id: I3d06bdc0e3e26bde0c0e646accd050364f9713b9

    envsetup: add a helper to fix "out/target/common" not being really common

    * out/target/common isn't really common, and if you do
      back to back builds for multiple devices, that is noticable.
    * Use out/target/common-$device instead, and link the appropriate
      dir to out/target/common every time lunch() is run, if
      ANDROID_FIXUP_COMMON_OUT is set.
    * Refer https://groups.google.com/forum/#!topic/android-building/ispbOgzoyg8
      for more info.

    Change-Id: I11e7df0e68e2a60ce32576f06397d60fc9465b60

    !!!!CHECK: build: add support for custom releasetools

    Change-Id: I2337559ac669bb5868708c4726cbacbf5713261a

    add support for overriding build.prop settings.

    Change-Id: Ie4224d608b7bcb0c2087bd77bc954f8f5f9b6495

    build: Rename ota packages from custom to omni.

    Change-Id: Idc344f404244cca466770f884dee361f38ea2ebe

    build: change custom -> omni in a few more places

    * these weren't changed when the transtition occured - fix them now

    Change-Id: I47bedb96ad63a41959baa98e1a265cb616d17918

    !!!!CHECK: releasetools: support more partitions and different fstab types

    * add BML support for Samsung legacy devices
    * add ext2, ext3 and vfat, f2fs support for EMMC
    * fix recovery.fstab for ADV recovery

    Change-Id: I6b76d2a21fe68096cf1b0cd850cdfb3a313370d1

    build: tools: add in roomservice

    This is a new implementation of roomservice
    use the new github search api to reduce the memory footprint, and make it less processor intensive
    allow for unofficial devices to fetch dependencies. just specify your github organization

    to fetch dependencies:
        add a file called 'omni.dependencies' to the root of your device tree
        an example configuration for the dependency file is:

    [
      {
        "repository": "android_device_sony_common",
        "target_path": "device/sony/common"
      },
      {
        "repository": "legacybop/android_hardware_qcom_display-legacy",
        "target_path": "hardware/qcom/display-legacy",
        "revision": "omni-4.3"
      }

    please note that comments can not go into this file. It must be valid json

    PatchSet 7:
      add support to change port script to another team with config
      finished pep8'ing
      more checks on manifest parsing

    Change-Id: I3d7a8d46d3effbb3d2480c136c9b6b6e610b9b2e

    Support fetching dependencies even if device tree fails.

    This is required when device tree depends on dependencies to lunch.

    Change-Id: If62cd9777caf768f8070570ca0835052645c6b20

    roomservice: Fix os.path.isdir calls

    Apparently on some Python installations
    it throws exception instead of returning False.

    Change-Id: I9d901e3260bab411cf3466346c421594f0922562

    roomservice: the search api is out of preview now

    Change-Id: I95f088daf8537784caf774ad6863037f7019f22d

    build: Don't copy APN list from emulator

    This list is severely incomplete and is overwriting the proper APN list in the vendor
    directory.

    Change-Id: I0e1b1d26e0cdf2df9a05462f0c9343bd3115635b

    roomservice: Add -f and --no-clone-bundle flags to repo sync

    Suppress scary-looking common warnings during resolving.

    Change-Id: I4337ec95992ad68ff4471b0d0b7346e933269503

    core_base: Remove "Home Sample"

    Change-Id: I690ab7d65fe02c0771c796d37d15f9ef857daaaf

    Allow prebuild APK's in Vendor

    Change-Id: I361c32fac1e003ec985ffe2282bf8ef922b11ac0

    ota: Disable downgrade check

    We want users to be able to downgrade their packages.

    Change-Id: I6bcbd4ee2a02640fe0855b0f1f197a02e914c927

    build: Add ro.omni.device

    Some devices, such as n7100, report under another product name
    in ro.product.name.
    As this is breaking delta updater, we introduce another variable
    to retrieve the actual device name as it was used to build.

    Change-Id: I96ecd189453ea9929884d094a7b846365506c397

    core: main: remove all the spam about including make files

    to disable showing the makefile includes:

        export HIDE_MAKEFILE_INCLUDES=y

    Change-Id: Ifd2ef0e239d16b169c572472416c2c31df62a367

    roomservice: Change default remote to omnirom

    Using the default of github results in people unable to use gerrit
    to submit patches to repos brought in by roomservice

    Change-Id: Idccd6c35bf81a35135e893ed03f6c5745059ec82

    roomservice: Fix handling of devices with _ in their name

    Currently, roomservice takes every _ in the device tree name and
    replaces it with /

    Instead, strip the device name (such as pollux_windy) from the repo
    name before replacing _ with / and then append it again when we're done

    Change-Id: Ieabe85ecd8829c959a7296e5cd73f577879c4ffc

    roomservice: urgent: add "+fork:true"

    Enable a device config to be found on github if it was forked

    thx @cybojenix

    Change-Id: Ic63f82b9ed754dcba17725f5aa75d0011896b09c

    installclean: remove *.md5sum

    Change-Id: Iba47421324bd6bbeabaa80eb66daf6a25621d6a2

    sepolicy: add omni common selinux policy inclusion

    It is required for https://gerrit.omnirom.org/#/c/4563

    Change-Id: I22c47febefd986274b53d69f89df6bff589c8ea0
    Signed-off-by: Humberto Borba <humberos@gmail.com>

    Roomservice: Search gerrit instead of github

    * Search for devices using gerrit api instead of github
    * Minor cleanups & fixes

    Change-Id: I54fc898f3c773f79936568818996ae5fab11e491

    build: Don't create recovery patch

    Change-Id: I00a9ca268ed3f326a0fa5a913bc112ec8b290550

    edify: update the RunBackup function

    set_perm was removed a few days ago, use the built in function for setting permissions
    TMPFS does not have xattr set, which is across most devices. dump the scripts into system so set_metadata will work

    Change-Id: I9ee00f15fa0be1eef31c5435b9d94845fd3aa630

    build: Don't use block mode by default, allow it to be chosen

    Currently this uses the same logic as backuptool (but inverted)

    i.e. block mode will be disabled in all cases where backuptool is enabled
    which is the current default for all Omni builds.

    Block mode is not needed now, and may never be needed for custom projects,
    as block mode is preparation for dm-verity, which is mostly pointless on
    devices with unlocked bootloaders since the kernel already has broken
    the chain of trust.

    TODO:  Determine if Nexus 9 *requires* blockmode.  If it does, this
    may need to be reworked to allow the device to specify blockmode.

    Change-Id: I36725b44f4066a43ec7e1615bd4b072f7eb3db28

    edify: fix the RunBackup function

    Remove 'self.UnpackPackageDir(system/addon.d, /system/addon.d)'
    since this would overwrite any existing backup script e.g. gapps

    Extract functions file to /tmp to not break existing
    backup script files that rely on that file beeing in /tmp

    Change-Id: I16741c17f30c28f5d537c693eaf43879d08f7ac1

    Fix grammar error in roomservice; Only add xml files in local_manifests

    Change-Id: Ia132acddd2761ec4c1bea7fb510e3bea306ea9fc

    build: Ensure /system unmounted at install start

    Account for the possibility that a user has mounted system manually
    before installing the FullOTA package.

    Change-Id: I97d0540676a7ce98762545e76ecb1a7f6335d204

    build: product: add new flag to exclude live wallpapers from build

    flag:
        TARGET_EXCLUDE_LIVEWALLPAPERS := true

    In general these entries are located on device repo, in omni_[device name].mk
    It should be declared before full_base_telephony.mk inherit statement

    Ps.
    Make sure that not exists packages declarations on specific device vendor repo.

    Signed-off-by: Humberto Borba <humberos@gmail.com>
    Change-Id: Ib77c3e2d13cc43981a0e12d853346abfc7549c67

    roomservice: support same repo using different path and revision

    Change-Id: Ifd47cbeab2ca7e99a117883e3a3ecb880581e110

    Conditionally create symlink /system/vendor if needed

    We don't need to build a vendor image in CM, just create the symlink
    for Nexus devices that use a vendor partition

    To use add BOARD_NEEDS_VENDORIMAGE_SYMLINK := true to BoardConfig.mk

     Conflicts:
        core/Makefile

    Change-Id: Id39ee89007af39346f0887796ed3cbad81765c46

    Fix symlink for system/vendor

    ref: http://review.cyanogenmod.org/#/c/117678/

    Change-Id: I8cacbd6916a73a69e98ddce22a2581f7c4834116

    roomservice: catch revision changes for existing entries

    delete existing roomservice file and restart in that case

    Change-Id: I2adc62da01fb75cd8ee5b13b5864043fb2594d0f

    roomservice: dynamically remove duplicate projects from roomservice manifest

    Change-Id: Idf4da69ca829fcd59d5264b05b9ed1c37d0195f8

    roomservice: Handling URLError exception during fetch device process

    BEFORE:

    humberos@fedora:/android/omni-6.0$ bib leo
    WARNING: Trying to fetch a device that's already there
    Traceback (most recent call last):
      File "build/tools/roomservice.py", line 319, in <module>
        fetch_dependencies(device)
      File "build/tools/roomservice.py", line 275, in fetch_dependencies
        fetch_device(device)
      File "build/tools/roomservice.py", line 287, in fetch_device
        git_data = search_gerrit_for_device(device)
      File "build/tools/roomservice.py", line 71, in search_gerrit_for_device
        response = urllib.request.urlopen(git_req)
      File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
        return opener.open(url, data, timeout)
      File "/usr/lib64/python2.7/urllib2.py", line 431, in open
        response = self._open(req, data)
      File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
        '_open', req)
      File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
        result = func(*args)
      File "/usr/lib64/python2.7/urllib2.py", line 1242, in https_open
        context=self._context)
      File "/usr/lib64/python2.7/urllib2.py", line 1199, in do_open
        raise URLError(err)
    urllib2.URLError: <urlopen error [Errno -5] No address associated with hostname>

    AFTER:

    humberos@fedora:/android/omni-6.0$ bib leo
    WARNING: Trying to fetch a device that's already there
    WARNING: No network connection available.

    Signed-off-by: Humberto Borba <humberos@gmail.com>
    Change-Id: I18950704c5b7d13553374611d164c2464c1ceab2

    roomservice: Create manifest entries from common repos

    With this change we will be able to read omni.dependencies from common repositories.

    Signed-off-by: Humberto Borba <humberos@gmail.com>
    Change-Id: Ic66ceead3601263df0c0e181a45b9ef7e7a32b77

    build: Fix roomservice during project validation

    Remove roomservice only if there is value to compare.

    Signed-off-by: Humberto Borba <humberos@gmail.com>
    Change-Id: Iefef90ba21c923243a6eff37229301f202988d9a

    core: Build Launcher3 instead of Launcher2

    Change-Id: I8efbeb480f0f1c4314c106c4d791fd1ffe3dc1a5

    build: Remove QuickSearchBox from core apps

    Change-Id: Ibc44a2e96fb9343a0ae898b460503e4adfeeef7f

    build: fix usage of qcom_target

    Change-Id: I5fbcf7d3b6de2a90a56cd0d695a97df2289830b2

    build: refactor setting CUSTOM_BUILD

    there is no real need to set this in check_product
    do it once afterwards it is clear what  will be

    Change-Id: I586bb3f94248f596cb0454d1a0e1a2a2a8f64a24

    build: change assertDevice as it was in 6

    TWRP doesnt like as it is now

    Change-Id: Ia23efd071698f08131cb42501f4b489c74b2e78a

    build: Add board platforms to qcom_utils

    Change-Id: I85458167bf2b9c04b029d09b87bf791ff4cfd04d

    buils: readd 8992 8994 and 8996 to QCOM_BOARD_PLATFORMS

    Change-Id: Iece3bac53ce10a9ae9b14202a2bf12f9cb9c731c

    build: fix BOARD_CUSTOM_BOOTIMG_MK

    Change-Id: I1b9fa7d8eb67bdcaaae7b55ca538b33545e73581

    build: remove dotfiles on a make clean as well

    * kati & ninja create dotfiles (example: .ninja_log) in out/

    Change-Id: I83ffd1c26a37f7ffef45fd4598435db93058ab67

    build: Add support for device tree in boot.img

    Add support for optional device tree image (dt.img)
    to boot and recovery images.  Some devices use kernel device
    tree and this adds the device tree image as a section within
    the boot/recovery images.

    Change-Id: I91431ef2f4b86485895678916e39a8572be878eb

    Fix case where boot/recovery.img were being built with wrong params.

    The boot and recovery images  now get built using the same params during ota package
    generation as during a normal build.

    Change-Id: I93d46e11a4245288f0e87c87a2e4bf45ac5aff69

    releasetools: Store and use the dt image file through target files

    Target files packages may be used for signing images separate from the
    build process. Store the device tree image file in the target files
    package so it can be used during the signing process.

    Change-Id: Ie8507121fa9c4ba57ecffeab05bd859ae5f5b788

    build: use the system's ccache by default

    * ccache gets updated semi-frequently and some builders would like
      to be able to take advantage of new features without having to
      rely on the prebuilt version getting updated

    * If a build system has ccache installed already, use that version
      instead of the prebuilt

    * @nathanchance edit: Replace which with command -v for portability,
      print which binary is being used, and apply the same logic to
      inline kernel compilation

    Change-Id: I8988c8a25fab3694d84633f957c2b92ce84cf69e

    Add msm8909 & msm8952 to QCOM_BOARD_PLATFORMS

    These used to be here, but apparently got lost in the bringup

    Change-Id: Ie7e8ab96d9e50efd2c21679756caab8f558952c6

    build: f2fs target rename for mkfs

    Change-Id: I031714f4fa171ca8d944da09e5142b44b0883b95

    build: remove OpenWnn

    this JapaneseIME

    Change-Id: I157d0293d6d84214d3d80faca043508932e1c2de

    build: Add msm8952 to MSM_VIDC_TARGET_LIST

    Change-Id: I8c2a4d22db8d14e078c7e07bb77c3a3817f5bf95

    [2/2] build: vendor sound config

    make sure default sound properties in vendor gets used
    little hack but we dont want to change all devices
    just for that

    Change-Id: I0ac900f500f38bfdf6935dfcbb6208f665cca83e

    Add ifeq flag to MINIGZIP for devices like tf101

    that can not use lzma to compress the kernel without causing problems
    but can not compile a recovery without a compression like lzma
    BOARD_NEEDS_LZMA_MINIGZIP := true

    Change-Id: I0cb8b126234fc5d20ceee83c2eb0266c37e4ff0f

    build: change default ro.com.android.dataroaming to false

    Change-Id: I7aad16a6bcdb55b954ed78cf77f5aa3072a3d53c

    base: move Telecomn TeleService and MmsService into telephony only

    Change-Id: I5c00181fabcdcfaefa22fd086313bf9fb18e2f3a

Change-Id: I866cedc246146db475c7513ba023ffba7a7e0de9